#!/bin/bash

#       *-------------------------------------------------------*
#       | Finds all cows compatible with the randomly generated |
#       | fortune cookie, and selects one randomly out of them. |
#       *-------------------------------------------------------*
#               o   ^__^
#                o  (OO)\_______
#                   (__)\       )\/\
#                       ||----w |
#                       ||     ||

# Find the fortune cookie
fortune_msg=$(fortune -c)
fortune_cookie=$(echo "$fortune_msg" | sed -n 1p | cut -c2- | rev | cut -c2- | rev)

i=0
check=0
# Find all cows compatible with the fortune_cookie, and choose one randomly.
while read -r cookie_line
do
  for cookie in $(echo "$cookie_line" | sed "s/,/ /g")
  do
    if [ $i -eq 0 ] && [ $check -eq 0 ]; then
      check=1
      continue
    fi
    cookie_arr[$i]="$cookie"
    ((i=i+1))
  done
done < <(grep "$fortune_cookie" ~/cpm/cookie_index)

if [ $i -eq 0 ]; then
  # Sadly, we don't have any cow associated with this cookie yet. Hence we use the "default" cow.
  echo "$fortune_msg" | tail -n +3 | cowsay
else
  rand=$(( RANDOM % i ))
  echo "$fortune_msg" | tail -n +3 | cowsay -f "${cookie_arr[$rand]}"
fi
