#!/bin/bash

#       *------------------------------------------*
#       | Use this script for setting up your barn |
#       *------------------------------------------*
#               o   ^__^
#                o  (OO)\_______
#                   (__)\       )\/\
#                       ||----w |
#                       ||     ||

# Check if all the requirements are met.
which cowsay &> /dev/null
if [ $? -ne 0 ]; then
  echo "Please install cowsay to proceed !!"
  exit 1
fi

which fortune &> /dev/null
if [ $? -ne 0 ]; then
  echo "Please install fortune to proceed !!"
  exit 1
fi

# Find the user's shell
shell=$(which $SHELL | rev | cut -f 1 -d '/' | rev)
echo ". ~/cpm/cow_selector" >> ~/."$shell"rc
