#!/bin/bash

#       *------------------------------------------*
#       | Use this script for setting up your barn |
#       *------------------------------------------*
#               o   ^__^
#                o  (OO)\_______
#                   (__)\       )\/\
#                       ||----w |
#                       ||     ||

# Check if all the requirements are met.
if ! which cowsay &> /dev/null
then
  echo "Please install cowsay to proceed !!"
  exit 1
fi

if ! which fortune &> /dev/null
then
  echo "Please install fortune to proceed !!"
  exit 1
fi

# Find the user's shell
shell=$(which "$SHELL" | rev | cut -f 1 -d '/' | rev)

# Remove all previous instances of cpm and make a new one
sed -i '/cow_selector/d' ~/."$shell"rc
echo ". ~/cpm/cow_selector" >> ~/."$shell"rc

echo "
    *------------------------------*
    | Your barn is ready. Enjoy !! |
    *------------------------------*
"
