#!/usr/bin/env bash

#       *------------------------------------------*
#       | Use this script for setting up your barn |
#       *------------------------------------------*
#               o   ^__^
#                o  (OO)\_______
#                   (__)\       )\/\
#                       ||----w |
#                       ||     ||

set -e
# Check if all the requirements are met.
if ! which cowsay &> /dev/null
then
  echo "Please install cowsay to proceed !!"
  exit 1
fi

if ! which fortune &> /dev/null
then
  echo "Please install fortune to proceed !!"
  exit 1
fi

# Find the user's shell
shell=$(which "$SHELL" | rev | cut -f 1 -d '/' | rev)

# Remove all previous instances of cpm and make a new one
# Following check is necessary for compatibility of sed across different OS
if [ "$(uname)" == "Darwin" ]; then
  # Using "-i" with sed on Mac OS X requires an extension for the backup file
  sed -i .bak '/cow_selector/d' "$HOME/.$shell"rc
else
  sed -i '/cow_selector/d' "$HOME/.$shell"rc
fi

echo ". $HOME/cpm/cow_selector" >> "$HOME/.$shell"rc

echo "
    *------------------------------*
    | Your barn is ready. Enjoy !! |
    *------------------------------*
"
